workflows:
  build:
    name: Build release APK and publish artifact
    instance_type: standard
    environment:
      flutter: stable
    scripts:
      - echo "Get dependencies"
      - flutter pub get
      - echo "Run analyzer (optional)"
      - flutter analyze || true
      - echo "Build release APK"
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - user@example.com
        on_build_success: true
        on_build_failure: false
